version: "3.9"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    # networks:
    #   - rentx_network

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    links:
      - database
    # networks:
    #   - rentx_network
    depends_on:
      - database

volumes:
  pgdata:
    driver: local

# networks:
#   rentx_network:
#     driver: bridge
